spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb
    username: root
    password: Timo13902025
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource: DEBUG
